import { useState } from 'react';
import { motion } from 'framer-motion';
import { Box, Button, Chip, Divider, MenuItem, Select, Stack, Typography } from '@mui/material';
import { Assessment, Download, TrendingUp } from '@mui/icons-material';
import { GlassCard, GlassPageHeader, GradientText } from '@components/glassmorphism/GlassComponents';
import { mockReports } from '../mockData';

export default function ReportsAnalyticsPage() {
  const [period, setPeriod] = useState('This month');
  const bars = [58, 72, 64, 86, 77, 94, 82, 100, 88, 96, 74, 91];
  return <Box sx={{ width: '100%', minWidth: 0 }}><motion.div initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }}><GlassPageHeader><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ xs: 'flex-start', md: 'center' }} gap={2}><Box><Typography variant="h4" sx={{ fontWeight: 800 }}><GradientText>Reports &amp; Analytics</GradientText></Typography><Typography color="text.secondary" sx={{ mt: .5 }}>Understand marketplace performance with clear, decision-ready insights.</Typography></Box><Stack direction="row" spacing={1}><Select size="small" value={period} onChange={(event) => setPeriod(event.target.value)}><MenuItem value="This week">This week</MenuItem><MenuItem value="This month">This month</MenuItem><MenuItem value="This quarter">This quarter</MenuItem></Select><Button variant="contained" startIcon={<Download />}>Export</Button></Stack></Stack></GlassPageHeader></motion.div><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)', lg: 'repeat(4, 1fr)' }, gap: 2, mt: 2 }}>{mockReports.map((report) => <GlassCard key={report.label} sx={{ p: 2.5 }}><Typography color="text.secondary" variant="body2">{report.label}</Typography><Typography variant="h5" fontWeight={800} sx={{ mt: .5 }}>{report.value}</Typography><Chip icon={<TrendingUp />} size="small" label={report.change} color="success" sx={{ mt: 1.5 }} /></GlassCard>)}</Box><GlassCard sx={{ mt: 2, p: { xs: 2, sm: 3 } }}><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="h6" fontWeight={800}>Marketplace performance</Typography><Typography variant="body2" color="text.secondary">Revenue trend · {period}</Typography></Box><Chip icon={<Assessment />} label="Live snapshot" color="primary" variant="outlined" /></Stack><Divider sx={{ my: 2.5 }} /><Box sx={{ height: 230, display: 'flex', alignItems: 'flex-end', gap: { xs: .5, sm: 1.5 }, px: { xs: 0, sm: 2 } }}>{bars.map((height, index) => <Box key={index} sx={{ flex: 1, minWidth: 12, height: `${height}%`, borderRadius: '8px 8px 3px 3px', background: index === bars.length - 1 ? 'var(--color-accent-grad)' : 'linear-gradient(180deg, rgba(99,102,241,.7), rgba(124,58,237,.22))', transition: 'height .4s ease', '&:hover': { opacity: .8, transform: 'translateY(-4px)' } }} />)}</Box><Stack direction="row" justifyContent="space-between" sx={{ mt: 1 }}><Typography variant="caption" color="text.secondary">Week 1</Typography><Typography variant="caption" color="text.secondary">Week 6</Typography></Stack></GlassCard></Box>;
}
