import React, { useState } from 'react';
import { useAdminStore } from '../../../store/useAdminStore';
import { DashboardSale } from '../../../services/adminDashboardApi';

interface Props { data: { period: string; total: number; items: DashboardSale[] }[]; }
export const LatestSales: React.FC<Props> = ({ data }) => {
  const { theme = 'dark', currency } = useAdminStore(); const dark = theme === 'dark'; const [period, setPeriod] = useState(data[0]?.period || ''); const active = data.find((item) => item.period === period) || { total: 0, items: [] }; const money = (value: number) => new Intl.NumberFormat(currency === 'INR' ? 'en-IN' : 'en-US', { style: 'currency', currency: currency === 'INR' ? 'INR' : 'USD', maximumFractionDigits: 0 }).format(value);
  return <section style={{ background: dark ? 'rgba(15,23,42,.78)' : '#FFF', border: `1px solid ${dark ? 'rgba(148,163,184,.16)' : '#E2E8F0'}`, borderRadius: 16, padding: 20, minWidth: 0 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center' }}><div><h3 style={{ color: dark ? '#F8FAFC' : '#0F172A', fontSize: 16, margin: 0 }}>Latest sales</h3><span style={{ color: dark ? '#94A3B8' : '#64748B', fontSize: 11 }}>Live transaction receipts</span></div><select value={period} onChange={(e) => setPeriod(e.target.value)} style={{ background: dark ? '#1E293B' : '#F8FAFC', color: dark ? '#FFF' : '#0F172A', border: `1px solid ${dark ? '#334155' : '#CBD5E1'}`, borderRadius: 8, padding: 7 }}>{data.map((item) => <option key={item.period} value={item.period}>{item.period}</option>)}</select></div><div style={{ color: '#10B981', fontSize: 24, fontWeight: 800, margin: '16px 0' }}>{money(active.total)}</div>{active.items.length === 0 ? <div style={{ color: dark ? '#94A3B8' : '#64748B', padding: 25, textAlign: 'center' }}>No sales data available.</div> : <div style={{ overflowX: 'auto' }}><table style={{ width: '100%', minWidth: 420, borderCollapse: 'collapse' }}><thead><tr>{['Name','Status','Date','Amount'].map((h) => <th key={h} style={{ textAlign: 'left', color: dark ? '#94A3B8' : '#64748B', fontSize: 10, padding: 9 }}>{h}</th>)}</tr></thead><tbody>{active.items.map((item) => <tr key={item.id} style={{ borderTop: `1px solid ${dark ? 'rgba(148,163,184,.12)' : '#E2E8F0'}` }}><td style={{ color: dark ? '#F8FAFC' : '#0F172A', fontSize: 12, fontWeight: 700, padding: 9 }}>{item.name}</td><td style={{ color: item.status === 'Completed' ? '#10B981' : item.status === 'Refunded' ? '#EF4444' : '#F59E0B', fontSize: 11, padding: 9 }}>{item.status}</td><td style={{ color: dark ? '#94A3B8' : '#64748B', fontSize: 11, padding: 9 }}>{item.date}</td><td style={{ color: item.amount >= 0 ? '#10B981' : '#EF4444', fontWeight: 800, fontSize: 12, padding: 9 }}>{money(item.amount)}</td></tr>)}</tbody></table></div>}</section>;
};
