import React, { useState } from 'react';
import { useAdminStore } from '../../../store/useAdminStore';
import { DashboardRegion } from '../../../services/adminDashboardApi';
import { ArrowDownRight, ArrowUpRight, Globe } from 'lucide-react';

interface Props { data: { period: string; items: DashboardRegion[] }[]; }
export const TopRegionSales: React.FC<Props> = ({ data }) => {
  const { theme = 'dark' } = useAdminStore(); const dark = theme === 'dark'; const [period, setPeriod] = useState(data[0]?.period || ''); const active = data.find((item) => item.period === period)?.items || []; const colors = ['#2563EB','#10B981','#A855F7','#F59E0B','#EC4899','#06B6D4'];
  return <section style={{ background: dark ? 'rgba(15,23,42,.78)' : '#FFF', border: `1px solid ${dark ? 'rgba(148,163,184,.16)' : '#E2E8F0'}`, borderRadius: 16, padding: 20, minWidth: 0 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center' }}><div style={{ display: 'flex', gap: 8, alignItems: 'center' }}><Globe size={18} color="#2563EB" /><div><h3 style={{ color: dark ? '#F8FAFC' : '#0F172A', fontSize: 16, margin: 0 }}>Top region sales</h3><span style={{ color: dark ? '#94A3B8' : '#64748B', fontSize: 11 }}>Geographic transaction share</span></div></div><select value={period} onChange={(e) => setPeriod(e.target.value)} style={{ background: dark ? '#1E293B' : '#F8FAFC', color: dark ? '#FFF' : '#0F172A', border: `1px solid ${dark ? '#334155' : '#CBD5E1'}`, borderRadius: 8, padding: 7 }}>{data.map((item) => <option key={item.period} value={item.period}>{item.period}</option>)}</select></div>{active.length === 0 ? <div style={{ color: dark ? '#94A3B8' : '#64748B', padding: 25, textAlign: 'center' }}>No regional data available.</div> : <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginTop: 18 }}>{active.map((item, index) => <div key={item.region}><div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12 }}><span style={{ color: dark ? '#E2E8F0' : '#334155', fontWeight: 700 }}>{item.flag || ''} {item.region}</span><span style={{ display: 'flex', gap: 7, alignItems: 'center', color: item.growth >= 0 ? '#10B981' : '#EF4444', fontSize: 10, fontWeight: 800 }}>{item.growth >= 0 ? <ArrowUpRight size={11} /> : <ArrowDownRight size={11} />}{Math.abs(item.growth)}% <strong style={{ color: dark ? '#F8FAFC' : '#0F172A' }}>{item.percentage}%</strong></span></div><div style={{ height: 6, background: dark ? '#1E293B' : '#E2E8F0', borderRadius: 999, marginTop: 5, overflow: 'hidden' }}><div style={{ width: `${item.percentage}%`, height: '100%', background: colors[index % colors.length], borderRadius: 999 }} /></div></div>)}</div>}</section>;
};
