import React, { useMemo, useState } from 'react';
import { useAdminStore } from '../../../store/useAdminStore';
import { useRFQStore } from '../../../store/useRFQStore';
import { PageTabs, TabItem } from '../../../components/common/PageTabs';
import { CheckCircle2, ChevronDown, ChevronUp, Clock, Eye, FileText, Search, X, XCircle } from 'lucide-react';
import { Quotation, RFQItem } from '../../../types';

export const AdminRFQManagementView: React.FC = () => {
  const { activeSubSection, setActiveSubSection, theme = 'dark' } = useAdminStore();
  const { rfqs = [], quotations = [], approveQuotation, rejectQuotation } = useRFQStore();
  const [search, setSearch] = useState('');
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [selectedRFQ, setSelectedRFQ] = useState<RFQItem | null>(null);
  const isDark = theme === 'dark';
  const c = { text: isDark ? '#F8FAFC' : '#0F172A', muted: isDark ? '#94A3B8' : '#64748B', panel: isDark ? 'rgba(17,24,39,.78)' : '#FFF', soft: isDark ? 'rgba(30,41,59,.72)' : '#F8FAFC', border: isDark ? 'rgba(148,163,184,.16)' : '#E2E8F0' };

  const currentTab = activeSubSection === 'RFQS_REQUESTS' ? 'RFQS_REQUESTS' : activeSubSection === 'RFQS_RESPONSES' ? 'RFQS_RESPONSES' : activeSubSection === 'RFQS_STATUS' ? 'RFQS_STATUS' : 'RFQS_ALL';
  const filteredRfqs = useMemo(() => {
    const query = search.toLowerCase();
    return rfqs.filter((rfq) => {
      const matchesSearch = `${rfq.productTitle} ${rfq.buyerCompany} ${rfq.category}`.toLowerCase().includes(query);
      const matchesTab = currentTab === 'RFQS_REQUESTS' ? rfq.status === 'OPEN' : currentTab === 'RFQS_RESPONSES' ? rfq.status === 'QUOTED' : currentTab === 'RFQS_STATUS' ? ['ACCEPTED', 'REJECTED', 'EXPIRED'].includes(rfq.status) : true;
      return matchesSearch && matchesTab;
    });
  }, [rfqs, search, currentTab]);

  const rfqTabs: TabItem[] = [
    { id: 'RFQS_ALL', label: 'All RFQs', badge: rfqs.length },
    { id: 'RFQS_REQUESTS', label: 'Open Requests', badge: rfqs.filter((rfq) => rfq.status === 'OPEN').length || undefined },
    { id: 'RFQS_RESPONSES', label: 'Active Bids', badge: rfqs.filter((rfq) => rfq.status === 'QUOTED').length || undefined },
    { id: 'RFQS_STATUS', label: 'Closed RFQs', badge: rfqs.filter((rfq) => ['ACCEPTED', 'REJECTED', 'EXPIRED'].includes(rfq.status)).length || undefined },
  ];

  const getQuotes = (rfqId: string) => quotations.filter((quote) => quote.rfqId === rfqId);
  const statusStyle = (status: RFQItem['status']) => status === 'OPEN' ? { color: '#34D399', bg: 'rgba(16,185,129,.14)' } : status === 'QUOTED' ? { color: '#FBBF24', bg: 'rgba(245,158,11,.14)' } : status === 'ACCEPTED' ? { color: '#60A5FA', bg: 'rgba(59,130,246,.14)' } : { color: '#F87171', bg: 'rgba(239,68,68,.14)' };
  const quoteStatusStyle = (status: Quotation['status']) => status === 'ACCEPTED' ? { color: '#34D399', bg: 'rgba(16,185,129,.14)' } : status === 'REJECTED' ? { color: '#F87171', bg: 'rgba(239,68,68,.14)' } : { color: '#FBBF24', bg: 'rgba(245,158,11,.14)' };
  const handleApprove = (quote: Quotation) => { approveQuotation(quote.id); if (selectedRFQ?.id === quote.rfqId) setSelectedRFQ({ ...selectedRFQ, status: 'ACCEPTED' }); };
  const handleReject = (quote: Quotation) => { rejectQuotation(quote.id); };

  const quoteRow = (quote: Quotation, compact = false) => {
    const status = quoteStatusStyle(quote.status);
    return <div key={quote.id} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap', background: c.soft, border: `1px solid ${c.border}`, borderRadius: 10, padding: compact ? 10 : 13 }}><div style={{ display: 'flex', alignItems: 'center', gap: 10, minWidth: 210, flex: 1 }}><img src={quote.supplierLogo} alt="" style={{ width: 30, height: 30, borderRadius: 8, objectFit: 'cover' }} /><div><strong style={{ color: c.text, display: 'block', fontSize: 12 }}>{quote.supplierName}</strong><span style={{ color: c.muted, fontSize: 10 }}>₹{(quote.unitPrice * 82).toLocaleString('en-IN')} / unit · {quote.estimatedDeliveryDays} day delivery</span></div></div><div style={{ display: 'flex', alignItems: 'center', gap: 9 }}><strong style={{ color: '#10B981', fontSize: 12 }}>₹{(quote.totalPrice * 82).toLocaleString('en-IN')}</strong><span style={{ color: status.color, background: status.bg, borderRadius: 999, padding: '5px 8px', fontSize: 10, fontWeight: 800 }}>{quote.status}</span>{quote.status === 'PENDING' && <><button onClick={() => handleApprove(quote)} style={{ display: 'inline-flex', alignItems: 'center', gap: 4, border: 0, borderRadius: 8, padding: '7px 9px', background: '#10B981', color: '#FFF', fontSize: 10, fontWeight: 800, cursor: 'pointer' }}><CheckCircle2 size={12} />Approve</button><button onClick={() => handleReject(quote)} style={{ display: 'inline-flex', alignItems: 'center', gap: 4, border: '1px solid rgba(248,113,113,.4)', borderRadius: 8, padding: '7px 9px', background: 'rgba(248,113,113,.1)', color: '#F87171', fontSize: 10, fontWeight: 800, cursor: 'pointer' }}><XCircle size={12} />Reject</button></>}</div></div>;
  };

  return <div style={{ display: 'flex', flexDirection: 'column', gap: 18, maxWidth: 1480, margin: '0 auto' }}><style>{`.rfq-row{transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}.rfq-row:hover{transform:translateY(-2px);box-shadow:0 14px 30px rgba(37,99,235,.12)!important;border-color:#60A5FA!important}`}</style>
    <PageTabs tabs={rfqTabs} activeTabId={currentTab} onChangeTab={(id) => setActiveSubSection(id as any)} theme={theme} />
    <div style={{ background: c.panel, border: `1px solid ${c.border}`, borderRadius: 12, padding: 10, display: 'flex', alignItems: 'center', gap: 8 }}><Search size={16} color="#60A5FA" /><input type="text" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Filter RFQs by item title, buyer company, industry category..." style={{ flex: 1, background: 'transparent', border: 0, color: c.text, fontSize: 13, outline: 0 }} /></div>
    <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>{filteredRfqs.map((rfq) => { const expanded = expandedId === rfq.id; const quotes = getQuotes(rfq.id); const status = statusStyle(rfq.status); return <div className="rfq-row" key={rfq.id} style={{ background: c.panel, border: `1px solid ${c.border}`, borderRadius: 14, padding: 16, boxShadow: '0 6px 18px rgba(2,6,23,.05)' }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 14, flexWrap: 'wrap' }}><div style={{ minWidth: 0, flex: 1 }}><h4 style={{ margin: 0, fontSize: 15, fontWeight: 800, color: c.text }}>{rfq.productTitle}</h4><div style={{ fontSize: 11, color: c.muted, marginTop: 5 }}>Broadcasted by <strong style={{ color: c.text }}>{rfq.buyerCompany}</strong> · Target ₹{(rfq.targetPrice * 82).toLocaleString('en-IN')} · {rfq.quantity} {rfq.unit}</div></div><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><span style={{ color: status.color, background: status.bg, borderRadius: 999, padding: '6px 9px', fontSize: 10, fontWeight: 800 }}>{rfq.status}</span><button onClick={() => setSelectedRFQ(rfq)} style={{ display: 'inline-flex', alignItems: 'center', gap: 5, border: '1px solid rgba(96,165,250,.45)', borderRadius: 8, padding: '7px 10px', background: 'rgba(96,165,250,.12)', color: '#60A5FA', fontSize: 11, fontWeight: 800, cursor: 'pointer' }}><Eye size={13} />View</button><button onClick={() => setExpandedId(expanded ? null : rfq.id)} aria-label="Toggle RFQ quotes" style={{ border: 0, background: 'transparent', color: c.muted, cursor: 'pointer', display: 'grid', placeItems: 'center' }}>{expanded ? <ChevronUp size={17} /> : <ChevronDown size={17} />}</button></div></div>{expanded && <div style={{ borderTop: `1px solid ${c.border}`, paddingTop: 13, marginTop: 14, display: 'flex', flexDirection: 'column', gap: 10 }}><div style={{ color: c.muted, fontSize: 12, lineHeight: 1.55 }}><strong style={{ color: c.text }}>Requirement:</strong> {rfq.description}</div><div style={{ display: 'flex', alignItems: 'center', gap: 6, color: c.muted, fontSize: 11 }}><Clock size={13} />Delivery by {rfq.expectedDeliveryDate} · {quotes.length} quote{quotes.length === 1 ? '' : 's'} received</div>{quotes.length ? quotes.map((quote) => quoteRow(quote, true)) : <div style={{ color: c.muted, fontSize: 11 }}>Waiting for supplier bids...</div>}</div>}</div>})}</div>
    {filteredRfqs.length === 0 && <div style={{ padding: 42, border: `1px dashed ${c.border}`, borderRadius: 14, textAlign: 'center', color: c.muted, fontSize: 13 }}>No RFQs match this view.</div>}

    {selectedRFQ && <div onClick={() => setSelectedRFQ(null)} style={{ position: 'fixed', inset: 0, zIndex: 1000, display: 'grid', placeItems: 'center', padding: 20, background: 'rgba(2,6,23,.7)', backdropFilter: 'blur(8px)' }}><div onClick={(event) => event.stopPropagation()} style={{ width: 'min(100%, 720px)', maxHeight: '90vh', overflowY: 'auto', background: isDark ? '#111827' : '#FFF', border: `1px solid ${c.border}`, borderRadius: 18, padding: 24, color: c.text, boxShadow: '0 24px 70px rgba(0,0,0,.35)' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16 }}><div><div style={{ color: '#60A5FA', fontSize: 10, fontWeight: 800, letterSpacing: '.08em' }}>RFQ DETAIL VIEW</div><h2 style={{ margin: '7px 0 4px', fontSize: 21 }}>{selectedRFQ.productTitle}</h2><div style={{ color: c.muted, fontSize: 12 }}>{selectedRFQ.id} · Created {selectedRFQ.createdAt}</div></div><button onClick={() => setSelectedRFQ(null)} aria-label="Close RFQ details" style={{ border: 0, borderRadius: 8, width: 32, height: 32, background: isDark ? 'rgba(255,255,255,.08)' : '#F1F5F9', color: c.muted, cursor: 'pointer' }}><X size={15} /></button></div><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 10, marginTop: 22 }}>{[['Buyer', selectedRFQ.buyerName], ['Company', selectedRFQ.buyerCompany], ['Location', selectedRFQ.buyerLocation], ['Category', selectedRFQ.category], ['Quantity', `${selectedRFQ.quantity} ${selectedRFQ.unit}`], ['Target price', `₹${(selectedRFQ.targetPrice * 82).toLocaleString('en-IN')}`], ['Expected delivery', selectedRFQ.expectedDeliveryDate], ['Quotes received', String(getQuotes(selectedRFQ.id).length)], ['Status', selectedRFQ.status]].map(([label, value]) => <div key={label} style={{ background: c.soft, borderRadius: 10, padding: 11 }}><div style={{ color: c.muted, fontSize: 10 }}>{label}</div><strong style={{ display: 'block', marginTop: 4, fontSize: 12, lineHeight: 1.4 }}>{value}</strong></div>)}</div><div style={{ marginTop: 16, padding: 14, borderRadius: 10, border: `1px solid ${c.border}`, color: c.muted, fontSize: 12, lineHeight: 1.6 }}><strong style={{ color: c.text }}>Requirement details</strong><br />{selectedRFQ.description}</div><div style={{ marginTop: 20 }}><div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 10 }}><FileText size={15} color="#60A5FA" /><h3 style={{ margin: 0, fontSize: 14 }}>Supplier quotations</h3></div><div style={{ display: 'flex', flexDirection: 'column', gap: 9 }}>{getQuotes(selectedRFQ.id).length ? getQuotes(selectedRFQ.id).map((quote) => quoteRow(quote)) : <div style={{ color: c.muted, fontSize: 12 }}>No quotations received yet.</div>}</div></div><button onClick={() => setSelectedRFQ(null)} style={{ width: '100%', marginTop: 22, border: 0, borderRadius: 9, padding: 11, background: '#2563EB', color: '#FFF', fontWeight: 800, cursor: 'pointer' }}>Close details</button></div></div>}
  </div>;
};
