import React, { useState } from 'react';
import { useAdminStore } from '../../../store/useAdminStore';
import { useOrderStore } from '../../../store/useOrderStore';
import { CreditCard, Download, Eye, X } from 'lucide-react';
import { OrderItem } from '../../../types';

export const AdminPaymentsView: React.FC = () => {
  const { orders } = useOrderStore();
  const { theme = 'dark' } = useAdminStore();
  const [selectedOrder, setSelectedOrder] = useState<OrderItem | null>(null);
  const dark = theme === 'dark';
  const c = { text: dark ? '#F8FAFC' : '#0F172A', muted: dark ? '#94A3B8' : '#64748B', panel: dark ? 'rgba(15,23,42,.78)' : '#FFF', soft: dark ? 'rgba(30,41,59,.72)' : '#F8FAFC', border: dark ? 'rgba(148,163,184,.16)' : '#E2E8F0' };
  const totalGMV = orders.reduce((sum, order) => sum + order.totalAmount * 82, 0);
  const commission = Math.round(totalGMV * .025);
  const escrow = Math.round(totalGMV * .45);
  const paid = totalGMV - escrow;
  const metrics = [['Total GMV transacted', totalGMV, '#34D399', '100% escrow backed'], ['Platform take-rate', commission, '#60A5FA', 'Net commission earnings'], ['Escrow locked in-transit', escrow, '#FBBF24', 'Awaiting delivery sign-offs'], ['Disbursed to suppliers', paid, '#C084FC', 'Direct bank NEFT / RTGS']];

  const money = (value: number) => `₹${value.toLocaleString('en-IN')}`;
  const getSettlement = (order: OrderItem) => {
    const gross = order.totalAmount * 82;
    const fee = Math.round(gross * .025);
    return { gross, fee, net: gross - fee };
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24, maxWidth: 1480, margin: '0 auto' }}>
      <style>{`.admin-card,.admin-table-row{transition:transform .18s ease,box-shadow .18s ease,background .18s ease}.admin-card:hover{transform:translateY(-3px);box-shadow:0 16px 35px rgba(2,6,23,.16)!important}.admin-table-row:hover{background:${dark ? 'rgba(59,130,246,.12)' : '#EFF6FF'}!important;box-shadow:inset 3px 0 #3B82F6}`}</style>
      <header><div style={{ color: '#60A5FA', fontSize: 11, fontWeight: 800, letterSpacing: '.1em', textTransform: 'uppercase' }}>Finance / Settlement operations</div><h1 style={{ color: c.text, fontSize: 'clamp(22px,2.4vw,30px)', margin: '8px 0 0', letterSpacing: '-.03em' }}>Payments & escrow settlements</h1><p style={{ color: c.muted, fontSize: 13, margin: '8px 0 0' }}>Track protected funds, automated payouts, and the platform commission ledger.</p></header>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(210px,1fr))', gap: 14 }}>{metrics.map(([label, value, color, note]) => <div className="admin-card" key={String(label)} style={{ background: c.panel, border: `1px solid ${c.border}`, borderRadius: 16, padding: 18, boxShadow: '0 8px 24px rgba(2,6,23,.08)' }}><div style={{ color: c.muted, fontSize: 11, fontWeight: 700 }}>{label}</div><strong style={{ display: 'block', color: String(color), fontSize: 25, marginTop: 8 }}>{money(Number(value))}</strong><span style={{ color: String(color), fontSize: 11, marginTop: 6, display: 'block' }}>{note}</span></div>)}</div>

      <section style={{ background: c.panel, border: `1px solid ${c.border}`, borderRadius: 16, overflow: 'hidden', boxShadow: '0 8px 24px rgba(2,6,23,.07)' }}>
        <div style={{ padding: '17px 20px', display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center', borderBottom: `1px solid ${c.border}` }}><div style={{ display: 'flex', gap: 10, alignItems: 'center' }}><CreditCard size={18} color="#60A5FA" /><div><h2 style={{ margin: 0, fontSize: 15, color: c.text }}>Escrow settlement audit trail</h2><span style={{ color: c.muted, fontSize: 11 }}>Live transaction ledger · {orders.length} records</span></div></div><button style={{ border: `1px solid ${c.border}`, background: c.soft, color: c.text, borderRadius: 9, padding: '9px 12px', fontSize: 11, fontWeight: 800, cursor: 'pointer' }}><Download size={13} style={{ verticalAlign: 'middle', marginRight: 5 }} />Export reconciliation</button></div>
        <div style={{ overflowX: 'auto' }}><table style={{ width: '100%', minWidth: 840, borderCollapse: 'collapse' }}><thead><tr style={{ background: c.soft }}>{['Transaction ref', 'Beneficiary supplier', 'Gross amount', 'Platform fee', 'Net payout', 'Status', 'Action'].map((heading) => <th key={heading} style={{ textAlign: 'left', padding: '13px 18px', color: c.muted, fontSize: 10, textTransform: 'uppercase', letterSpacing: '.05em' }}>{heading}</th>)}</tr></thead><tbody>{orders.map((order) => { const { gross, fee, net } = getSettlement(order); const settled = order.status === 'DELIVERED'; return <tr className="admin-table-row" key={order.id} style={{ borderBottom: `1px solid ${c.border}` }}><td style={{ padding: '15px 18px', color: c.text, fontWeight: 800, fontSize: 12 }}>TXN-ESC-{order.id.toUpperCase()}<small style={{ display: 'block', color: c.muted, fontWeight: 500, marginTop: 4 }}>Order #{order.orderNumber}</small></td><td style={{ padding: '15px 18px', color: c.text, fontSize: 12 }}>{order.supplierName}</td><td style={{ padding: '15px 18px', color: c.text, fontWeight: 800 }}>{money(gross)}</td><td style={{ padding: '15px 18px', color: '#60A5FA', fontWeight: 700 }}>{money(fee)}</td><td style={{ padding: '15px 18px', color: '#10B981', fontWeight: 800 }}>{money(net)}</td><td style={{ padding: '15px 18px' }}><span style={{ color: settled ? '#34D399' : '#FBBF24', background: settled ? 'rgba(16,185,129,.12)' : 'rgba(245,158,11,.12)', borderRadius: 999, padding: '5px 9px', fontSize: 10, fontWeight: 800 }}>{settled ? 'SETTLED' : 'ESCROW HOLD'}</span></td><td style={{ padding: '15px 18px' }}><button onClick={() => setSelectedOrder(order)} style={{ display: 'inline-flex', alignItems: 'center', gap: 5, border: '1px solid rgba(96,165,250,.45)', borderRadius: 8, padding: '7px 11px', background: 'rgba(96,165,250,.12)', color: '#60A5FA', fontSize: 11, fontWeight: 800, cursor: 'pointer' }}><Eye size={13} />View</button></td></tr>; })}</tbody></table></div>
      </section>

      {selectedOrder && <div onClick={() => setSelectedOrder(null)} style={{ position: 'fixed', inset: 0, zIndex: 1000, display: 'grid', placeItems: 'center', padding: 20, background: 'rgba(2,6,23,.7)', backdropFilter: 'blur(8px)' }}><div onClick={(event) => event.stopPropagation()} style={{ width: 'min(100%, 620px)', maxHeight: '90vh', overflowY: 'auto', background: dark ? '#111827' : '#FFF', border: `1px solid ${c.border}`, borderRadius: 18, padding: 24, color: c.text, boxShadow: '0 24px 70px rgba(0,0,0,.35)' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16 }}><div><div style={{ color: '#60A5FA', fontSize: 10, fontWeight: 800, letterSpacing: '.08em' }}>TRANSACTION DETAILS</div><h2 style={{ margin: '7px 0 4px', fontSize: 21 }}>TXN-ESC-{selectedOrder.id.toUpperCase()}</h2><div style={{ color: c.muted, fontSize: 12 }}>Order #{selectedOrder.orderNumber}</div></div><button onClick={() => setSelectedOrder(null)} aria-label="Close transaction details" style={{ border: 0, borderRadius: 8, width: 32, height: 32, background: dark ? 'rgba(255,255,255,.08)' : '#F1F5F9', color: c.muted, cursor: 'pointer' }}><X size={15} /></button></div>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginTop: 22 }}>{[['Supplier', selectedOrder.supplierName], ['Buyer', selectedOrder.buyerName], ['Product', selectedOrder.productTitle], ['Order date', selectedOrder.orderDate], ['Quantity', `${selectedOrder.quantity}`], ['Unit price', money(selectedOrder.unitPrice * 82)], ['Payment status', selectedOrder.paymentStatus.replace('_', ' ')], ['Order status', selectedOrder.status], ['Tracking number', selectedOrder.trackingNumber || 'Not assigned'], ['Transaction type', 'Escrow settlement']].map(([label, value]) => <div key={label} style={{ background: c.soft, borderRadius: 10, padding: 12 }}><div style={{ color: c.muted, fontSize: 10 }}>{label}</div><strong style={{ display: 'block', marginTop: 5, color: c.text, fontSize: 12, lineHeight: 1.4 }}>{value}</strong></div>)}</div>
        <div style={{ marginTop: 16, padding: 14, borderRadius: 11, border: `1px solid ${c.border}` }}><div style={{ color: c.muted, fontSize: 11, fontWeight: 800, marginBottom: 10 }}>SETTLEMENT BREAKDOWN</div>{[['Gross amount', getSettlement(selectedOrder).gross, c.text], ['Platform fee · 2.5%', getSettlement(selectedOrder).fee, '#60A5FA'], ['Net supplier payout', getSettlement(selectedOrder).net, '#10B981']].map(([label, value, color]) => <div key={String(label)} style={{ display: 'flex', justifyContent: 'space-between', gap: 12, padding: '9px 0', borderBottom: `1px solid ${c.border}`, fontSize: 12 }}><span style={{ color: c.muted }}>{label}</span><strong style={{ color: String(color) }}>{money(Number(value))}</strong></div>)}</div>
        <div style={{ marginTop: 16, padding: 14, borderRadius: 11, background: selectedOrder.status === 'DELIVERED' ? 'rgba(16,185,129,.1)' : 'rgba(245,158,11,.1)', color: selectedOrder.status === 'DELIVERED' ? '#34D399' : '#FBBF24', fontSize: 12, fontWeight: 800 }}>{selectedOrder.status === 'DELIVERED' ? '✓ Settlement completed after delivery confirmation.' : '◷ Funds remain in escrow until delivery sign-off.'}</div>
        <div style={{ marginTop: 16, color: c.muted, fontSize: 11, lineHeight: 1.6 }}><strong style={{ color: c.text }}>Delivery address</strong><br />{selectedOrder.deliveryAddress}</div><button onClick={() => setSelectedOrder(null)} style={{ width: '100%', marginTop: 22, border: 0, borderRadius: 9, padding: 11, background: '#2563EB', color: '#FFF', fontWeight: 800, cursor: 'pointer' }}>Close details</button>
      </div></div>}
    </div>
  );
};
