import React, { useMemo, useState } from 'react';
import { useAdminStore } from '../../../store/useAdminStore';
import { Star, MessageSquare } from 'lucide-react';

export const AdminReviewsView: React.FC = () => {
  const { reviews, updateReviewStatus, theme = 'dark' } = useAdminStore();
  const [filter, setFilter] = useState<'ALL' | 'PUBLISHED' | 'FLAGGED' | 'HIDDEN'>('ALL');
  const dark = theme === 'dark';
  const c = { text: dark ? '#F8FAFC' : '#0F172A', muted: dark ? '#94A3B8' : '#64748B', panel: dark ? 'rgba(15,23,42,.78)' : '#FFF', soft: dark ? 'rgba(30,41,59,.72)' : '#F8FAFC', border: dark ? 'rgba(148,163,184,.16)' : '#E2E8F0' };
  const visible = useMemo(() => reviews.filter((r) => filter === 'ALL' || r.status === filter), [reviews, filter]);
  return <div style={{ display: 'flex', flexDirection: 'column', gap: 24, maxWidth: 1480, margin: '0 auto' }}>
    <style>{`.review-card{transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}.review-card:hover{transform:translateY(-3px);box-shadow:0 16px 35px rgba(2,6,23,.16)!important;border-color:#60A5FA!important}`}</style>
    <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 18, flexWrap: 'wrap' }}><div><div style={{ color: '#F59E0B', fontSize: 11, fontWeight: 800, letterSpacing: '.1em', textTransform: 'uppercase' }}>Trust & quality / moderation</div><h1 style={{ color: c.text, fontSize: 'clamp(22px,2.4vw,30px)', margin: '8px 0 0', letterSpacing: '-.03em' }}>Reviews & customer ratings</h1><p style={{ color: c.muted, fontSize: 13, margin: '8px 0 0' }}>Keep marketplace feedback authentic, useful, and policy-compliant.</p></div><div style={{ display: 'flex', gap: 5, padding: 4, background: c.soft, border: `1px solid ${c.border}`, borderRadius: 11 }}>{(['ALL', 'PUBLISHED', 'FLAGGED', 'HIDDEN'] as const).map((s) => <button key={s} onClick={() => setFilter(s)} style={{ border: 0, borderRadius: 8, padding: '9px 11px', background: filter === s ? '#F59E0B' : 'transparent', color: filter === s ? '#FFF' : c.muted, fontSize: 10, fontWeight: 800, cursor: 'pointer' }}>{s}</button>)}</div></header>
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,330px),1fr))', gap: 16 }}>{visible.map((rev) => <article className="review-card" key={rev.id} style={{ background: c.panel, border: `1px solid ${rev.status === 'FLAGGED' ? 'rgba(245,158,11,.5)' : c.border}`, borderRadius: 16, padding: 18, boxShadow: '0 8px 24px rgba(2,6,23,.07)', display: 'flex', flexDirection: 'column', gap: 14 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><div style={{ display: 'flex', gap: 2 }}>{[0, 1, 2, 3, 4].map((i) => <Star key={i} size={15} fill={i < rev.rating ? '#F59E0B' : 'none'} color="#F59E0B" />)}</div><span style={{ color: rev.status === 'PUBLISHED' ? '#34D399' : rev.status === 'FLAGGED' ? '#FBBF24' : '#F87171', background: rev.status === 'PUBLISHED' ? 'rgba(16,185,129,.12)' : rev.status === 'FLAGGED' ? 'rgba(245,158,11,.12)' : 'rgba(239,68,68,.12)', padding: '5px 9px', borderRadius: 999, fontSize: 10, fontWeight: 800 }}>{rev.status}</span></div><div><h2 style={{ color: c.text, fontSize: 15, margin: 0 }}>{rev.targetTitle}</h2><div style={{ color: c.muted, fontSize: 11, marginTop: 5 }}>By {rev.authorName} · {rev.authorCompany} · {rev.date}</div></div><p style={{ margin: 0, padding: 13, borderRadius: 11, background: c.soft, color: c.text, fontSize: 12, lineHeight: 1.55 }}><MessageSquare size={13} color="#60A5FA" style={{ verticalAlign: 'middle', marginRight: 6 }} />“{rev.comment}”</p><div style={{ display: 'flex', gap: 8, marginTop: 'auto' }}>{rev.status !== 'PUBLISHED' && <button onClick={() => updateReviewStatus(rev.id, 'PUBLISHED')} style={{ flex: 1, border: 0, borderRadius: 9, padding: 10, background: '#10B981', color: '#FFF', fontWeight: 800, cursor: 'pointer' }}>Approve</button>}{rev.status !== 'HIDDEN' && <button onClick={() => updateReviewStatus(rev.id, 'HIDDEN')} style={{ flex: 1, border: '1px solid rgba(239,68,68,.35)', borderRadius: 9, padding: 10, background: 'rgba(239,68,68,.1)', color: '#F87171', fontWeight: 800, cursor: 'pointer' }}>Hide review</button>}</div></article>)}</div>
  </div>;
};
